<a href="https://colab.research.google.com/github/Gopi-cybers/personal-portfolio/blob/master/Netflix_Data_analyst_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import libraries and data

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px # Used to data visulations
from textblob import TextBlob

In [2]:
df= pd.read_csv('/content/netflix_titles.csv.zip')

Checking number of rows and columns in data

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Checking content available in data

In [4]:
df.shape

(8807, 12)

How to check columns name of data set

In [5]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

Taking the cunts of vatings available

In [6]:
x=df.groupby(['rating']).size().reset_index(name='counts')
x

      rating  counts
0     66 min       1
1     74 min       1
2     84 min       1
3          G      41
4      NC-17       3
5         NR      80
6         PG     287
7      PG-13     490
8          R     799
9      TV-14    2160
10      TV-G     220
11     TV-MA    3207
12     TV-PG     863
13      TV-Y     307
14     TV-Y7     334
15  TV-Y7-FV       6
16        UR       3

Creating the piechart based on content rating

In [7]:
piechart=px.pie(x,values='counts',names='rating',title='Distribution of Ratings on netflix')
piechart.show()

Analysis the top5 directors on the Netflix

In [8]:
df['director']=df['director'].fillna('director not specified')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,director not specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,director not specified,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,director not specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [9]:
director_list=df['director'].str.split(',',expand=True).stack()

In [10]:
print(director_list)

0     0           Kirsten Johnson
1     0    director not specified
2     0           Julien Leclercq
3     0    director not specified
4     0    director not specified
                    ...
8802  0             David Fincher
8803  0    director not specified
8804  0           Ruben Fleischer
8805  0              Peter Hewitt
8806  0               Mozez Singh
Length: 9612, dtype: object

In [11]:
director_list=director_list.to_frame()

In [12]:
print(director_list)

                             0
0    0         Kirsten Johnson
1    0  director not specified
2    0         Julien Leclercq
3    0  director not specified
4    0  director not specified
...                        ...
8802 0           David Fincher
8803 0  director not specified
8804 0         Ruben Fleischer
8805 0            Peter Hewitt
8806 0             Mozez Singh

[9612 rows x 1 columns]

In [13]:
director_list.columns=['director']

In [14]:
print(director_list)

                      director
0    0         Kirsten Johnson
1    0  director not specified
2    0         Julien Leclercq
3    0  director not specified
4    0  director not specified
...                        ...
8802 0           David Fincher
8803 0  director not specified
8804 0         Ruben Fleischer
8805 0            Peter Hewitt
8806 0             Mozez Singh

[9612 rows x 1 columns]

In [30]:
directors= director_list.groupby(['director']).size().reset_index(name='total count')

In [16]:
directors

                       director  total count
0                Aaron Moorhead            2
1                   Aaron Woolf            1
2      Abbas Alibhai Burmawalla            1
3              Abdullah Al Noor            1
4           Abhinav Shiv Tiwari            1
...                         ...          ...
5116                Çagan Irmak            1
5117           Ísold Uggadóttir            1
5118        Óskar Thór Axelsson            1
5119           Ömer Faruk Sorak            2
5120               Şenol Sönmez            2

[5121 rows x 2 columns]

In [17]:
directors = directors[directors.director != 'director not specified']

In [18]:
print(directors)

                       director  total count
0                Aaron Moorhead            2
1                   Aaron Woolf            1
2      Abbas Alibhai Burmawalla            1
3              Abdullah Al Noor            1
4           Abhinav Shiv Tiwari            1
...                         ...          ...
5116                Çagan Irmak            1
5117           Ísold Uggadóttir            1
5118        Óskar Thór Axelsson            1
5119           Ömer Faruk Sorak            2
5120               Şenol Sönmez            2

[5120 rows x 2 columns]

In [19]:
directors = directors.sort_values(by=['total count'], ascending=False)

In [20]:
print(directors)

                 director  total count
4020        Rajiv Chilaka           22
4067          Raúl Campos           18
261             Jan Suter           18
3235         Marcus Raboy           16
4651          Suhas Kadav           16
...                   ...          ...
2330  Ivan Andrew Payawal            1
610    Songyos Sugmakanan            1
611          Sonia Dauger            1
612        Sophie Sartain            1
2335           Ivona Juka            1

[5120 rows x 2 columns]

In [21]:
top5Directors = directors.head()

In [22]:
print(top5Directors)

           director  total count
4020  Rajiv Chilaka           22
4067    Raúl Campos           18
261       Jan Suter           18
3235   Marcus Raboy           16
4651    Suhas Kadav           16

In [23]:
top5Directors=top5Directors.sort_values(by=['total count'])

In [24]:
barchart=px.bar(top5Directors,x='total count',y='director',title='Top 5 Directors on Netflix')

In [25]:
barchart.show()

In [26]:
from os import name
df['cast']=df['cast'].fillna('cast not specified')
cast_df=pd.DataFrame()
cast_df=df['cast'].str.split(',',expand=True).stack()
cast_df=cast_df.to_frame()
cast_df.columns=['actor']
actors=cast_df.groupby(['actor']).size().reset_index(name='count')
actors= actors[actors.actor != 'cast not specified']
actors=actors.sort_values(by='count',ascending=False)
top5Actors=actors.head()
top5Actors=top5Actors.sort_values(by='count',)
barchart2=px.bar(top5Actors,x='count',y='actor',title='Top 5 Actors on Netflix')
barchart2
barchart2.show()

In [27]:
df1=df[['type','release_year']]
df1=df1.rename(columns={"release_year":"release year","type":"type"})
df2=df1.groupby(['release year','type']).size().reset_index(name='totalcounts')
df2

     release year     type  totalcounts
0            1925  TV Show            1
1            1942    Movie            2
2            1943    Movie            3
3            1944    Movie            3
4            1945    Movie            3
..            ...      ...          ...
114          2019  TV Show          397
115          2020    Movie          517
116          2020  TV Show          436
117          2021    Movie          277
118          2021  TV Show          315

[119 rows x 3 columns]

In [28]:
df2=df2[df2['release year']>=2000]
graph= px.line(df2,x='release year',y='totalcounts',color='type',title='Trend of content on netflix')
graph.show()

Sentiment Analysis of Netflix content

In [29]:


# Step 1: Take needed columns
df3 = df[['release_year', 'description']].copy()

# Step 2: Create sentiment column properly (NO LOOP MISTAKES)
df3['sentiment'] = df3['description'].astype(str).apply(
    lambda x: 'Positive' if TextBlob(x).sentiment.polarity > 0
    else ('Negative' if TextBlob(x).sentiment.polarity < 0 else 'Neutral')
)

# Step 3: Group data correctly
df_grouped = df3.groupby(['release_year', 'sentiment']).size().reset_index(name='totalcounts')

# Step 4: Filter years
df_grouped = df_grouped[df_grouped['release_year'] >= 2005]

# Step 5: Plot correct graph
fig = px.bar(
    df_grouped,
    x='release_year',
    y='totalcounts',
    color='sentiment',
    title='Sentiment of content on Netflix'
)

fig.show()